"""add created_by assigned_to to shipments

Revision ID: 466df412b743
Revises: d74be4f52c44
Create Date: 2026-01-10 16:23:30.154347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466df412b743'
down_revision: Union[str, Sequence[str], None] = 'd74be4f52c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('shipments', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shipments_assigned_to'), 'shipments', ['assigned_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_assigned_to'), table_name='shipments')
    op.drop_column('shipments', 'assigned_to')
    op.drop_column('shipments', 'created_by')
    # ### end Alembic commands ###
